library(foreign)
library(MASS)

wt <- read.table("temp3.txt", header=T)

rr.bisquare <- rlm(T~0+q, data=wt, psi=psi.bisquare, method="MM", maxit=100)
rr.bisquare2 <- rlm(CH4~0+T, data=wt, psi=psi.bisquare, method="MM", maxit=100)
rr.bisquare3 <- rlm(CH4~0+q, data=wt, psi=psi.bisquare, method="MM", maxit=100)
rr.bisquare4 <- rlm(CH4~0+CO2, data=wt, psi=psi.bisquare, method="MM", maxit=100)

jpeg("wt.jpeg")
  par(mfrow=c(2,2))
  plot(wt$q,wt$T)
  abline(rr.bisquare)
  plot(wt$q,wt$T, xlim=c(-8,8), ylim=c(-4,4))
  abline(rr.bisquare)
  plot(wt$T,wt$CH4)
  abline(rr.bisquare2)
  plot(wt$T,wt$CH4, xlim=c(-4,4), ylim=c(-0.05,0.05))
  abline(rr.bisquare2)
dev.off()

jpeg("wt2.jpeg")
  par(mfrow=c(2,2))
  plot(wt$q,wt$CH4)
  abline(rr.bisquare3)
  plot(wt$q,wt$CH4, xlim=c(-8,8), ylim=c(-0.05,0.05))
  abline(rr.bisquare3)
  plot(wt$CO2,wt$CH4)
  abline(rr.bisquare4)
  plot(wt$CO2,wt$CH4, xlim=c(-8,8), ylim=c(-0.05,0.05))
  abline(rr.bisquare4)
dev.off()

write(rr.bisquare$coefficients, "out1.txt")
write(rr.bisquare2$coefficients, "out2.txt")
write(rr.bisquare3$coefficients, "out3.txt")
write(rr.bisquare4$coefficients, "out4.txt")
